<?php

namespace MiamDomainBundle\Repository;

/**
 * BranchArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
