<?php

namespace MiamDomainBundle\Repository;

/**
 * IngredientDensityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientDensityRepository extends \Doctrine\ORM\EntityRepository
{
}
