<?php

namespace MiamDomainBundle\Repository;

/**
 * ShopBranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopBranchRepository extends \Doctrine\ORM\EntityRepository
{
}
